
# change the followings to match your Github username and repo name
baseurl: "/perspectives-on-el-salvador-2" # the name of your github repo
url: "https://isabakes.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Perspectives on El Salvador"
description: Jekyll site for the Isabella Baker's Perspectives on El Salvador Project @ Boston College

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# nav bar settings and links
nav-menu:
  - title: Home
    link: index
  - title: About
    link: about
  - title: American Studies Project
    link: american-studies
    submenu:
      - title: Rincón Mágico
        link: rincon-magico
      - title: What's in a Name
        link: whats-in-a-name
      - title: Adorning Ideologies
        link: adorning-ideologies
      - title: Bibliography
        link: as-bibliography
  - title: Intro to Digitial Humanities
    link: intro-to-dh
    submenu:
      - title: The Bad Example
        link: the-bad-example
      - title: Because I Spoke Out
        link: because-i-spoke-out
      - title: The Art of Poetry
        link: the-art-of-poetry
      - title: Madrigal
        link: madrigal
      - title: Megalomania
        link: megalomania
      - title: César Vallejo
        link: cesar-vallejo
  - title: Salvadoran Digital Resources
    link: salvadoran-digital-resources
    submenu:
      - title: Salvadoran Archives
        link: salvadoran-archives
      - title: Timeline
        link: timeline
  
# sets whether a search bar appears on the site header
# NOTE, you will have to increase the site of teh $site-header-height in _sass/theme-settings.scss to to see the search bar
search-bar: false

hide-footer: false # set to true to hide the footer
footer-message: Perspectives on El Salvador | CC BY-NC License
footer-submessage:  By Isabella Baker, Boston College
footer-submessage-link: https://ib.bc.edu

# google-analytics: // if you want to use Google analytics, include your ID here

# sets number of items display per page, if using a blog
paginate: 5

include:
  - _pages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-paginate
    - jekyll-postcss-v2
